---
- name: Set up Bearer Token authentication
  block:
  - name: Log into RH SSO API
    uri:
      url: https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token
      body_format: form-urlencoded
      method: POST
      body:
        grant_type: refresh_token
        client_id: rhsm-api
        refresh_token: "{{ rh_offline_api_token }}"
    register: rh_sso_reg
    until: rh_sso_reg is not failed
    retries: 30
    delay: 10

  - name: Set up temporary fact for RH Offline Token exchange
    set_fact:
      tmp_auth_header_fact:
        Authorization: "Bearer {{ rh_sso_reg.json.access_token }}"

  - name: Set up headers for Bearer authentication
    set_fact:
      compiled_uri_headers: "{{ tmp_auth_header_fact }}"