apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: csr-auto-approver-binding
subjects:
- kind: ServiceAccount
  name: csr-service-account
  namespace: csr-auto-approver
roleRef:
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
  name: csr-auto-approver
